---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nanominer
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: nanominer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nanominer
    spec:
      serviceAccountName: nanominer
      securityContext:
        fsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      containers:
        - name: nanominer
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          image: "myhomemail565/nanominer:3.8.5"
          imagePullPolicy: IfNotPresent
          resources:
            {}
          volumeMounts:
            - name: config
              mountPath: /nanominer/config.ini
              subPath: config.ini
      volumes:
        - name: config
          configMap:
            name: nanominer
